apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-product-service
  template:
    metadata:
      labels:
        app: db-product-service
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "productdb"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-data
      volumes:
      - name: postgres-data
        emptyDir: {} # Replace with a PersistentVolumeClaim for production
---
apiVersion: v1
kind: Service
metadata:
  name: db-product-service
spec:
  selector:
    app: db-product-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
